title: InkSlate
author: Anindita Basu
description: "Your handwriting tells a story. InkSlate listens to it."

github:
  repository_url: https://github.com/AninditaBasu/inkslate

remote_theme: AninditaBasu/parchment-docs
plugins:
  - jekyll-remote-theme
parchment:
  preset: palmleaf